### ISSUE TITLE
Invite by email > Email validate works in sequence

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1108]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1051
- Input 2 emails:
+ An email has been already invited to the workspace
+ An email has an invalid template

# Actual Result
When pressing on the "Send" button, it displays only an error with the second email. 
If the user removes the second email, then presses the "Send" button again, it displays an error with the first email.

https://user-images.githubusercontent.com/69950655/143012878-edb35615-9ffa-40ec-8807-899ff100f238.mp4

# Expected Result
It should display the error at the same time for all invalid emails
# Environment
- Build version: 3.0.9
- Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
Because of there is a bug from server side (it has not validated email), I can not make the validation in sequence. (see API error on the attached image). 
cc: @romanesko and @RomaricMourgues 

My implemented validation flow is:
1. Validate email in mobile app side. If there is an error, notice to user an error icon side by side email
2. When all emails format are valid, send to API. After that, if it's failed, the mobile side will display error icon side by side email

So I think the above flow is good enough. Once the backend updated, I will remove validation in the mobile side. What do you think @tlle14 ?

<img width="1038" alt="Screen Shot 2021-11-26 at 7 59 14 PM" src="https://user-images.githubusercontent.com/29337364/143584895-29daf205-598a-4728-a704-eb9f2f9b0003.png">
