### ISSUE TITLE
Magic Link/Receive > Opening the magic link doesn't redirect to Inviting screen on Mobile App

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1144]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1022
Use case:
```
Given I am not a Twake user 
And I have the application on my mobile installed
When I look to signup with a magic link
Then I open the link, the mobile application turns on
And I see a page explaining that I can join the workspace
And I click on "join"
And I am redirected to the signup form (console)
Then I am redirected to Twake chat in the workspace related to the magic link
```
- The app is already installed 
- The user is not logged in
- The Magic Link is generated from Twake Web (by copying the newest link in the textbox) 
![image](https://user-images.githubusercontent.com/69950655/146177355-9211e7d0-7c3f-4ec6-825e-e76bdd3a8793.png)

# Actual Result
When opening the magic link, it opens the app with the Welcome screen instead of the Inviting screen as described in the story
Besides, the previous link (generated from web) is working correctly since it opens the Inviting screen. 

https://user-images.githubusercontent.com/69950655/146183101-06c3aa81-b31f-40fd-9f9f-5cf0cc865c53.mp4

# Expected Result
When opening the magic link, in case the app has been installed, it should display the Inviting screen. 
This issue may relate to https://github.com/linagora/Twake/issues/1822

# Environment
- Build version: 3.0.10
- Device:
iPhone Xr - iOS 14.4 - 6.46 inch
- QA environment

**Comment by huynguyennovem** [comment]
@tlle14 : This is because of the generated link on the Web is not the same format as Mobile. 
- On the web: `/join/<token>`
- On the mobile: `?join=<token>`

So, when using the link from the web, `<token>` can not be extracted from url by different format.

I have already followed the url format from document here and the Web should do the same: https://github.com/linagora/Twake/issues/1712#issuecomment-950299642
