### ISSUE TITLE
Uploading > The file attachment button is disabled after 2 times deny the access permission on a specified phone

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1158]
# Precondition
- Story: https://github.com/linagora/Twake-Mobile/issues/1137
- File uploading version 1
- Device: Samsung A51

# Actual Result
After 2 times denying the access permission to the phone, the file attached button is not working anymore, even after restarting the App.
https://user-images.githubusercontent.com/69950655/146901464-2c316f4e-ec2a-4945-b752-7aa28430974d.mp4

# Expected Result
Please investigate. 
I've tried on other Android phones, it always opens the access permission popup if the previous time the user denied the access. 

# Environment
- Build version: 3.0.10
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inches
- QA environment

**Comment by huynguyennovem** [comment]
On Android, when user denied permission request twice, they have to go to app's Settings to grant permission.
And because we haven't UI for this. So, I will get the idea from this screen that we had here: https://zpl.io/254Qmon. It will look like this:

![Screen Shot 2021-12-28 at 4 49 13 PM](https://user-images.githubusercontent.com/29337364/147553424-bd4d5b5e-ac96-477f-815b-a97d8c68a99f.png)

What do you think? @BastiaanVanGaalen @tlle14 

If we need to change this UI later, I will update.

**Comment by tlle14** [comment]
CC: @BenoitTallandier how do you think? 
@huynguyennovem : as I described, the issue happens only on Samsung A51. Other phones always display the popup.

**Comment by tlle14** [comment]
Retest pass! 
After asking access permission 2 times, it displays a pop-up as Huy said.
