### ISSUE TITLE
Magic Link/ Manage > Magic link is reset after it is copied to the clipboard

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1238]
# Precondition
Create a new workspace

# Actual Result
After copying the magic link to the clipboard, the link is regenerated. 
That means the user always receives an expired link

https://user-images.githubusercontent.com/69950655/150968678-8e384795-8e2a-47e8-aca9-4fc25af60777.mp4

# Expected Result
The link is only regenerated when clicking the regenerate button

# Environment
- Build version: 3.0.12
- Device:
Samsung Galaxy A51- Android 11
iPhone 12 - ios 15.1
- QA environment

**Comment by huynguyennovem** [comment]
> "After copying the magic link to the clipboard, the link is regenerated.
That means the user always receives an expired link" 

-> This is speculation. All generated links are valid until them expired by time currently. Pls confirm with BE team for this.

And we should separate this ticket into two:
1. Should it be auto generated link when open the page? (may be need clarify in another User Story)
2. Magic link is expire or failed

------------
FYI: The token format has changed recently by API, due to all magic links are failed. Need wait a while for BE team.

**Comment by tlle14** [comment]
Thank @huynguyennovem 
We should wait until the backend is done. Then I will retest.
