### ISSUE TITLE
"Share by" issues

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake-Mobile#1309]
- [ ] Bug when searching channel if I select one it doesn't go back to the main view and if I go back to the main view I should see the selected channel in the list
- [ ] We must save the latest sharing location
- [ ] List of companies the show more pas is not scrollable, why only 8 in the horizontal list why not putting all of them here ?
- [ ] After coming back to the app sometime message doesn’t display (websocket not yet reconnected ?)
- [ ] Could we order channels by last activity ? Last time I tested it wasn't clear the order

**Comment by huynguyennovem** [comment]
Thanks for logging these issues. 
- As I see, most of them seem like a change request for feature/story, so we also need to update story in order to others can understand the feature. 
@BenoitTallandier can you pls help to update these changes into story #1178 ?

- `why only 8 in the horizontal list why not putting all of them here ?`
-> This is defined by story. And I also think 8-10 limitation is good for a horizontal list (most of applications are same)

- `After coming back to the app sometime message doesn’t display (websocket not yet reconnected ?)`
-> It would be better if you could give me some more information like:
    - the message does not show part (only file or just text) or the whole message you have shared?
    - do they happen often?
    - what are the steps to reproduce them (it would be best if there was a video of this error)

**Comment by BenoitTallandier** [comment]
Hi, 
Yes, I'll update the story

**Comment by RomaricMourgues** [comment]
@EvGen94 ping
