### ISSUE TITLE
Add emoji short name to UTF-16 conversion on proxy

### ISSUE THREAD

**Issue by bobs4462** [linagora/Twake-Mobile#270]
Currently emojis are stored in inconsistent format, and uses both non-portable emoji short names and UTF-16 codes. 
We need to convert emoji short names to their respective UTF-16 format on proxy.

In channels entity there's an icon field which might contain short names
In messages - reactions (map structure), keys are usually short names
In message bodies, well let's leave it out for now

**Comment by RomaricMourgues** [comment]
Little update on this topic. After studying APIs from Slack and also Github it seems named emojis is what industry uses.
So we will continue using names emojis BUT we need to define a specific dictionary of emojis.
Currently we use this dictionary: https://raw.githubusercontent.com/missive/emoji-mart/master/data/apple.json

**Comment by RomaricMourgues** [comment]
This dictionary will be in place in the backend and a parameter in request will convert emojis to UTF8 for mobile.
Emojis must be stored in :named: format when possible in backend and db.

**Why ?** Because some desktop don't support emojis, so on desktop we need to convert to images using emoji-mart. On mobile you don't have this issue so you can directly get UTF16 emojis from backend.

**Comment by bobs4462** [comment]
So you have to implement not only backend to mobile conversion, but also mobile to backend conversion, because all the emoji picking libraries use UTF-16 code directly. Emojis are currently used in reactions, channel icons, and inlined in message text. The last one is problematic I think, as it requires one to parse entire message for emoji coded and map them to their short names, but when rendering the message on mobile you have to convert it back and inline it again...

**Comment by RomaricMourgues** [comment]
Yes I am aware of the issues, but you understand the desktop issue too :p 

We need a common dictionary for named<->utf8 , and I need to check what happen at slack if you choose an emoji that only exists on ios and not on android for instance. And by the way we have a backlog issue about "custom emojis" too.

Because all devices has different set of emojis + the ability to have named custom emojis from images, we need to create a dictionary and also create custom emoji picker for reactions and channels emojis. (messages emojis can contain non compatible emojis this is less critical)

**Comment by bobs4462** [comment]
For now we are converting emojis from short name to utf-16 on proxy, but not the reverse. So most channel icons and reactions should display fine on mobile app. We are going to implement reverse conversion as soon as we have a stable emojiset to convert to.

**Comment by RomaricMourgues** [comment]
👍 

For the record, on Twake we use:
```
"emoji-mart": "3.0.0", //Currently in use
"emojione": "4.5.0", //Depreciated
```
Sorry for using both... but I suppose the final emojiset will be a merge of these two ones.

**Comment by bobs4462** [comment]
Not relevant anymore, have to move to one consistent emojimap across all the applications.
