### ISSUE TITLE
Displaying a non-fit splash screen and isn't displaying a channel list when starting app.

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#367]
# Precondition
Install a new app

# Actual Result
1. When opening the app, it displays a non-fit splash screen.
2. When starting the app, it displays a grey rectangle in the workspace instead of a channel list

https://user-images.githubusercontent.com/69950655/111408748-532edb80-8708-11eb-8a9e-1e96f8220b99.mp4

# Expected Result
1. The splash screen should fit the mobile screen.
2. The channel list should display normally

# Environment
Android App
Screensize 6.5 inches
Build version: 2.2.9-3

**Comment by bobs4462** [comment]
Hi @tlle14 
The splash screen behavior is weird :). Can you please specify the phone you used to catch such a bug?

As for the grey rectangle, did you first delete the app before installing fresh one, as I wrote in the email?

**Comment by tlle14** [comment]
Hi @bobs4462 
1. About the splash screen, I can reproduce it on another device with the same screen size. I guess it's a responsive issue. 
2. About a grey rectangle, I removed the old app before installing the new one. I'm sure about it.

**Comment by bobs4462** [comment]
Hmmm, it's so strange that your phone just logs in immediately (without asking for credentials), the issue is directly related to the fact that your phone didn't clean the local storage for the application when you deleted the app itself. It seems to be Samsung only issue, because we cannot reproduce this storage persistence bug (https://stackoverflow.com/questions/42538180/app-cache-directory-is-not-deleted-after-uninstall-samsung-galaxy-tab-a) on other Android phones. Anyway the grey rectangle should not be reproducible after the first reinstall, can you confirm?

**Comment by tlle14** [comment]
I cannot reproduce issue 2 anymore. 
But issue 1, If the screen is responsive, the logo will be enlarged on the splash screen. 
If the screen is not responsive, the splash screen seems not to fit. 
- xiaomi note 9 -  6.53 inches - not fit
- Samsung A51 - 6.5 inches - not fit
- Nokia 2.3 - 6.2 inches - fit
- iPhone 7 - 4.7 inches - fit

**Comment by bobs4462** [comment]
Alright, thanks for the info, I'll investigate the issue 1

**Comment by tlle14** [comment]
Retest pass!
Thank @manhduc-nguyen 
![image](https://user-images.githubusercontent.com/69950655/114806941-bd9e6e80-9dcf-11eb-9f22-41b03cfe4a22.png)
