### ISSUE TITLE
Cannot login when the user has not invited to any workspace

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#378]
# Precondition
User is added into the company
User has not invited to any workspace

# Actual Result
When user login on the mobile app, it displays a loading screen infinitely
https://user-images.githubusercontent.com/69950655/112614583-022f8d80-8e54-11eb-9bbe-743fef01d28d.mp4

# Expected Result
It should have a message for user to know he isn't added to any workspace. 
As on web: 
![image](https://user-images.githubusercontent.com/69950655/112615002-884bd400-8e54-11eb-8209-a91408529fad.png)

# Environment
QA environment
Both iOS and Android App
Build version: 2.2.9-4

**Comment by bobs4462** [comment]
@tlle14 Can you please provide us with user test user (without workspaces) credentials and the server you are connecting to, so it'll be easier for us to debug the issue.

**Comment by tlle14** [comment]
> @tlle14 Can you please provide us with user test user (without workspaces) credentials and the server you are connecting to, so it'll be easier for us to debug the issue.

sure, I sent it on Twake

**Comment by bobs4462** [comment]
Hi @tlle14, we talked to @BenoitTallandier and according to him, now it should be impossible to create a user without workspace, because upon creation any user will be added to the default workspace automatically. I checked it on beta.twake.app, and can confirm that's indeed the observed behavior, i.e. new user is added to default workspace but not to any channel. 

Can I ask you to check this again please, and provide us with test data if you find any differences, so we can discuss it with Twake Core team.

**Comment by bobs4462** [comment]
@tlle14 ping :)

**Comment by tlle14** [comment]
Hi @bobs4462 
I confirm that this case is no longer happens since they changed the business. 
The new user will be added to the default channel of the default workspace in the company
Thanks for your answer!


https://user-images.githubusercontent.com/69950655/115651719-ec7b8e00-a355-11eb-981c-b9d750d7116f.mp4
