### ISSUE TITLE
Cannot display avatar on the chat screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#518]
# Actual Result
The user avatar cannot display on the chat screen. It always shows as a grey dot.
![image](https://user-images.githubusercontent.com/69950655/116366922-fe1ad500-a830-11eb-9fa3-f8f865466358.png)

# Expected Result
The user avatar should display, even it is an uploaded photo or a default avatar

# Environment
Both ios and android app
Build version: 2.2.9-7
QA environment

**Comment by bobs4462** [comment]
The problem is that aws servers (where images are stored) are not always available, like 90% of the time in Russia. I think if you were to test it from France or other country from western Europe you wouldn't encounter such a problem, but for the rest of the world, it is what is :)

But alas it's not up to us to solve this issue. @RomaricMourgues I highlighted the issue more than 4 month ago, it still persists. When we launch the app in debug mode, we observe a lot errors indicating that aws server request timed out.

**Comment by RomaricMourgues** [comment]
Every new pictures is stored in France now :)

**Comment by bobs4462** [comment]
```
CacheManager: Failed to download file from https://s3.eu-west-3.amazonaws.com/twake.eu-west-3/public/uploads/prfl/9d50c7cb2371cec7a9ec3edef90c4ba0.jpg with error:
SocketException: OS Error: Connection refused, errno = 111, address = s3.eu-west-3.amazonaws.com, port = 41756
```

Still the images are stored somewhere on amazon servers, judging by the urls at least

**Comment by RomaricMourgues** [comment]
Yes but I mean every new users not is QA will have the images in ovh.

**Comment by bobs4462** [comment]
So I guess, @tlle14, new users will have their avatars displayed, as for the old ones, well old ones have to reupload their avatars it seems :). I any case there's no way to solve this issue by developers. It seems more like DevOps task, either to migrate data, or to distribute it across the globe.

**Comment by bobs4462** [comment]
Can we close this issue?

**Comment by tlle14** [comment]
The issue is no longer existing
