### ISSUE TITLE
Create Workspace > When typing the email, cannot scroll the screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#713]
# Precondition
The member list is long (have many rows)

# Actual Result
When typing the email, the user cannot scroll the current screen (to see the workspace name.)
https://user-images.githubusercontent.com/69950655/124700174-75967000-df16-11eb-8885-ca0e94ff81b4.mp4

# Expected Result
User should be able to scroll to the screen when the member list is long

# Environment
- Build version: 3.0.2
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by EvGen94** [comment]
Good evening @tlle14 
The member list is scrollable. In this case, there is nothing to scroll because the entire list fits on the screen.

When there is not enough space on the screen and the user's keyboard closes part of the screen, the upper part of the screen is hidden as in the design, if you continue to add the user further and again run out of space, then you can scroll the list, if you close the keyboard, the upper part of the screen will become visible again.

**Comment by tlle14** [comment]
Hi @EvGen94 
I guess it will have a better vision if the scroll is for the screen instead of the email list. 
By the way, we need advice from our UX designer @BastiaanVanGaalen

**Comment by BastiaanVanGaalen** [comment]
We should certainly give the user an opportunity to scroll while input stays in focus with blinking cursor inside)

**Comment by tlle14** [comment]
Thank @EvGen94 and @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/a1f94606-a39b-4338-a029-a4297e6a5c9e/video01e26065_1bbb_4d6c_ac9d_893e0f2a719bvideo__2_.mp4
