### ISSUE TITLE
The App doesn't run in the background

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#769]
# Precondition
Login to the app

# Actual Result
When logging in to the app, User left the app running in the background. After a few minutes later, he opens the app and sees it doesn't have any update since he left it in the background running. Sometimes the app fails to login or syncing data.
https://user-images.githubusercontent.com/69950655/126425688-b0adc4d1-2e0e-46df-951f-2481ec3f5130.mp4

# Expected Result
The App should be able to process when in the background running

# Environment
- Build version: 3.0.3
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- Production

**Comment by bobs4462** [comment]
Hmmm, I don't think that problem is solvable. You see, when the operating system (android or iOS) detects that application has been moved to background, it completely removes it from queue to access hardware resources (processor, network etc.) and puts it to kind of a sleep, which means the applications code is just stops executing completely and only can be resumed when the application is moved back to foreground. That's how mobile OSes work...

**Comment by tlle14** [comment]
Do you know the maximum time the app can live in background running?

**Comment by bobs4462** [comment]
@tlle14 I think this issue is not relevant anymore, as data sync takes 10 seconds max

**Comment by tlle14** [comment]
Thanks. This is an invalid issue
