### ISSUE TITLE
Mention > Mentioning displays userID in the twacode 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#889]
# Actual Result
When mentioning a user in twacode, after submitted, the mentioning exposes userID
https://user-images.githubusercontent.com/69950655/132498104-a0d9d842-141f-4002-ab47-5e572d9c328e.mp4

# Expected Result
It shouldn't display userID of the mentioning in twacode

# Environment

- Build version: 3.0.6
- Device:
Samsung Galaxy A51 - Android 11 - 6.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
- QA environment

**Comment by bobs4462** [comment]
@tlle14 have to tried to do the same thing on web? :)

**Comment by tlle14** [comment]
> @tlle14 have to tried to do the same thing on web? :)

I didn't. I cannot login web in a week

**Comment by bobs4462** [comment]
You can login using incognito mode, btw, is the Twake team aware of the issue?

**Comment by tlle14** [comment]
I've tried incognito mode and wasn't successful. 
But why do you ask to try the same thing on Web? Do you think it is from the Backend?

**Comment by bobs4462** [comment]
I mean, on web it works the same

**Comment by RomaricMourgues** [comment]
@hantt12 we do have this issue in backlog.
It happens when your username is the same as your full-name (in web, in mobile I think it happens for every users because you don't have the WYSIWYG input yet) and only in code blocks.
We consider it as low issue for now because mention in code block is not widely used.
