### ISSUE TITLE
Direct chat icons are loading slowly

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#96]
# Actual Result
Avatar of direct messages are slowly appearing
https://streamable.com/wrrub7

# Expected Result
It should be displayed as if those direct chats are always there
It might be the issue of the dev server or internet connection. But please be investigate if we can improve.

# Enviornment
app-release[2020-12-14]

**Comment by bobs4462** [comment]
@RomaricMourgues I think we can close these issue, because not much can be done about it for now, do you agree?
Although we can implement a local caching of the images, but that's not going to solve the issue entirely, because we have get the images first before we can cache them, in Russia we still receive images 1 out 10 attempts to load them on average.

**Comment by RomaricMourgues** [comment]
Use the cached image widget from Flutter at least but yes this 1 out of 10 issue is the real problem, let see if it still happen once we are on ovh instead of AWS.

**Comment by bobs4462** [comment]
Alright, let's wait for the OVH migration then

**Comment by tlle14** [comment]
The direct chat icon is loading rapidly on Production. I should close this issue.
